name: Build, Push, and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  # Job 1: Build and Push the Docker Image
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/user-service:${{ github.sha }}
          # We keep the no-cache option to prevent old code from being used
          no-cache: true

  # Job 2: NEW! This job updates the deployment repository
  update_deployment:
    # This job will only run if the 'build' job was successful
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the INFRASTRUCTURE repository
      - name: Checkout infra config repository
        uses: actions/checkout@v3
        with:
          # Use the new PAT to get write access
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: HariomKhaladkar/edtech-infra-config

      # Step 2: Update the image tag in the ArgoCD manifest file
      - name: Update image tag
        # This 'sed' command finds the line with 'tag:' and replaces the value
        # with the full commit SHA of the code we just built.
        run: |
          sed -i 's|tag: ".*"|tag: "${{ github.sha }}"|' argocd-apps/user-service-app.yaml

      # Step 3: Commit and push the change
      - name: Commit and push the updated tag
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add .
          # Check if there are changes to commit to avoid errors on no-op runs
          if ! git diff-index --quiet HEAD; then
            git commit -m "AUTODEPLOY: Update image tag to ${{ github.sha }}"
            git push
          else
            echo "No changes to commit."
          fi