name: Verify Docker Username

on:
  push:
    branches: [ "main" ]

jobs:
  verify:
    runs-on: ubuntu-latest
    # We create an environment variable for this job, safely loading the secret.
    env:
      USERNAME_SECRET: ${{ secrets.DOCKERHUB_USERNAME }}
    steps:
      - name: Check if username secret matches the correct value
        # Now, we check the environment variable instead of the secret directly.
        if: ${{ env.USERNAME_SECRET == 'hariom1804' }}
        run: echo " SUCCESS The username secret MATCHES!"

      - name: Show error if username does not match
        # We do the same check here.
        if: ${{ env.USERNAME_SECRET != 'hariom1804' }}
        run: echo " FAILURE The username secret DOES NOT MATCH! Please check for typos or extra spaces in your GitHub Secret."