
name: Debug Docker Credentials

on:
  push:
    branches: [ "main" ]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print Docker Hub Username
        run: echo "The username being used is --->${{ secrets.DOCKERHUB_USERNAME }}<---"