 
# A descriptive name for your workflow
name: Build and Push Docker Image

# This section defines the trigger for the workflow.
# It will run on every push to the 'main' branch.
on:
  push:
    branches: [ "main" ]

# This section defines the jobs to be run. We have one job called 'build'.
jobs:
  build:
    # The type of virtual machine to run the job on. 'ubuntu-latest' is a standard choice.
    runs-on: ubuntu-latest

    # These are the individual steps the job will perform in sequence.
    steps:
      # Step 1: Checks out your repository code so the workflow can access it.
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Logs into Docker Hub using the secrets you just created.
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Builds your Docker image and pushes it to Docker Hub.
      # The image will be tagged with the unique Git commit SHA for versioning.
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/user-service:${{ github.sha }}