name: Build, Push, and Deploy Course Service

on:
  push:
    branches: [ "main" ]
    paths:
      - 'course-service/**'

jobs:
  build-course-service:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push course-service image
        uses: docker/build-push-action@v4
        with:
          context: ./course-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/course-service:${{ github.sha }}
          no-cache: true

  update-course-deployment:
    needs: build-course-service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout infra config repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: HariomKhaladkar/edtech-infra-config
      - name: Update image tag in course-service manifest
        run: |
          # THIS IS THE CRITICAL FIX:
          # The command now targets the correct file.
          sed -i 's|tag: ".*"|tag: "${{ github.sha }}"|' argocd-apps/course-service-app.yaml
      - name: Commit and push the updated tag
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m "AUTODEPLOY(course-service): Update image tag to ${{ github.sha }}"
            git push
          else
            echo "No changes to commit."
          fi